[log]
path = "/tmp/databrary_log"
level = "DEBUG" #PANIC FATAL ERROR WARN INFO DEBUB

[database]
host = "localhost"
dbname = "databrary"
port = "5432"
user = "postgres"
password = "mysecretpassword"
sslmode = "disable"
schema = "src/github.com/databrary/databrary/db/schema/master_sql"

[ssl]
cert = "/home/$USER/go/src/github.com/databrary/databrary/config/ssl/cert.pem"
key = "/home/$USER/go/src/github.com/databrary/databrary/config/ssl/key.pem"

[redis]
address = "localhost:6379"
password = "mysecretpassword"
secret = "mysecret"
size = 10

[cookie]
hash_key = "hashkey"
block_key = "blockkey"

[address]
scheme = "https"
domain = "172.22.236.163"
backend_port = "3444"
frontend_port = "3000"

[static]
path = "./public"